import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Image from "next/image";
import Link from "next/link";
import { FiLogOut } from "react-icons/fi";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navItems = [
  { label: "Users", href: "/users" },
  { label: "Logs", href: "/logs" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname =
    typeof window !== "undefined" ? window.location.pathname : "";
  return (
    <html lang="en" style={{ colorScheme: "light" }}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-foreground`}
        style={{ background: "#fff", color: "#171717" }}
      >
        <div className="flex min-h-screen w-full">
          <aside className="w-64 bg-gray-50 border-r border-gray-300 shadow-sm shadow-gray-200 flex flex-col p-6 overflow-y-auto max-h-screen">
            <div className="mb-8 flex flex-col items-center">
              <Image
                src="/logo.svg"
                alt="Logo"
                width={164}
                height={48}
                priority
              />
            </div>
            <nav className="flex flex-col gap-2 mt-4 flex-1">
              {navItems.map((item) => (
                <Link
                  key={item.href}
                  href={item.href}
                  className={`px-4 py-2 rounded text-base font-medium transition-colors ${
                    pathname === item.href
                      ? "bg-blue-100 text-blue-700"
                      : "hover:bg-gray-100 text-gray-800"
                  }`}
                >
                  {item.label}
                </Link>
              ))}
            </nav>
            <div className="mt-auto p-2 px-4 flex flex-col items-start border border-gray-200 hover:border-gray-300 rounded-md">
              <span className="flex items-center justify-between gap-2 text-base font-semibold text-gray-800">
                Username{" "}
                <Link
                  href="/login"
                  className="text-blue-600 text-xs hover:underline mt-1 flex items-center"
                >
                  <span className="sr-only">logout</span>
                  <FiLogOut className="w-4 h-4" />
                </Link>
              </span>
            </div>
          </aside>
          <main className="w-full">{children}</main>
        </div>
      </body>
    </html>
  );
}
