import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/app/globals.css";
import Image from "next/image";
import { UserBox } from "@/components/UserBox";
import { SidebarNav } from "../../components/SidebarNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname =
    typeof window !== "undefined" ? window.location.pathname : "";
  return (
    <html lang="en" style={{ colorScheme: "light" }}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white text-foreground`}
        style={{ background: "#fff", color: "#171717" }}
      >
        <div className="flex min-h-screen w-full">
          <aside className="w-64 bg-gray-50 border-r border-gray-300 shadow-sm shadow-gray-200 flex z-10 flex-col p-6 overflow-y-auto max-h-screen">
            <div className="mb-8 flex flex-col items-center">
              <Image
                src="/logo.svg"
                alt="Logo"
                width={164}
                height={48}
                priority
              />
            </div>
            <SidebarNav />
            <UserBox />
          </aside>
          <main className="w-full">{children}</main>
        </div>
      </body>
    </html>
  );
}
